/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("task").del();
  await knex("task").insert([
    {
      id: 1,
      place_name: "新千歳空港 レンタカーカウンター",
      type: "移動",
      detail:
        "到着ロビーを出たら右に進み、予約したレンタカー会社の受付へ。予約番号：HKD-98765。",
      item: "運転免許証, 予約確認メール画面",
      URL_photo: "https://images.example.com/chitose-airport.jpg",
      URL_home: "https://www.example.com/hokkaido-rentacar",
      URL_googlemap: "https://maps.google.com/?q=New+Chitose+Airport",
      previous_place_id: null,
      arrive_time: "2026-08-10 10:30:00",
      departure_time: "2026-08-10 11:15:00",
      related_project_id: 1,
    },
    {
      id: 2,
      place_name: "ファーム富田",
      type: "観光",
      detail:
        "ラベンダー畑を散策。ショップでラベンダーソフトクリームを食べる。混雑が予想されるため、早めに移動。",
      item: "カメラ, 帽子, 日焼け止め",
      URL_photo: "https://images.example.com/farm-tomita.jpg",
      URL_home: "https://www.farm-tomita.co.jp",
      URL_googlemap: "https://maps.google.com/?q=Farm+Tomita",
      previous_place_id: 1,
      arrive_time: "2026-08-10 13:30:00",
      departure_time: "2026-08-10 15:30:00",
      related_project_id: 1,
    },
    {
      id: 3,
      place_name: "青い池（美瑛）",
      type: "観光",
      detail:
        "立ち枯れたカラマツと青い水面のコントラストを撮影。売店で青いプリンの購入を検討。",
      item: "カメラ, 三脚",
      URL_photo: "https://images.example.com/blue-pond.jpg",
      URL_home: "https://biei-shirogane-bluepond.jp",
      URL_googlemap: "https://maps.google.com/?q=Shirogane+Blue+Pond",
      previous_place_id: 2,
      arrive_time: "2026-08-10 16:15:00",
      departure_time: "2026-08-10 17:00:00",
      related_project_id: 1,
    },
    {
      id: 4,
      place_name: "白金温泉 ホテルプラザ",
      type: "宿泊",
      detail:
        "1泊目の宿。源泉かけ流しの露天風呂でドライブの疲れを癒やす。夕食は19:00から和食会席。",
      item: "着替え, 充電器",
      URL_photo: "https://images.example.com/shirogane-hotel.jpg",
      URL_home: "https://www.example.com/shirogane-hotel",
      URL_googlemap: "https://maps.google.com/?q=Shirogane+Onsen+Hotel",
      previous_place_id: 3,
      arrive_time: "2026-08-10 17:30:00",
      departure_time: "2026-08-11 09:00:00",
      related_project_id: 1,
    },
    {
      id: 5,
      place_name: "旭山動物園",
      type: "観光",
      detail:
        "もぐもぐタイム（ペンジン・ホッキョクグマ）の時間を園内掲示板で最初にチェックする。",
      item: "入園券（事前購入済）, 飲み物",
      URL_photo: "https://images.example.com/asahiyama-zoo.jpg",
      URL_home: "https://www.city.asahikawa.hokkaido.jp/asahiyamazoo/",
      URL_googlemap: "https://maps.google.com/?q=Asahiyama+Zoo",
      previous_place_id: 4,
      arrive_time: "2026-08-11 10:00:00",
      departure_time: "2026-08-11 14:00:00",
      related_project_id: 1,
    },
    {
      id: 6,
      place_name: "あさひかわラーメン村",
      type: "食事",
      detail:
        "少し遅めの昼食。ミニラーメンをハーフサイズでハシゴする予定。梅光軒か青葉を候補に。",
      item: "現金（食券用）",
      URL_photo: "https://images.example.com/ramen-mura.jpg",
      URL_home: "http://www.ramen村.com",
      URL_googlemap: "https://maps.google.com/?q=Asahikawa+Ramen+Village",
      previous_place_id: 5,
      arrive_time: "2026-08-11 14:30:00",
      departure_time: "2026-08-11 15:30:00",
      related_project_id: 1,
    },
    {
      id: 7,
      place_name: "札幌エクセルホテル東急",
      type: "宿泊",
      detail:
        "2泊目の宿。チェックイン後、車をホテルの駐車場に預けてすすきのへ移動する。",
      item: "宿泊バウチャー",
      URL_photo: "https://images.example.com/tokyu-hotel-sapporo.jpg",
      URL_home: "https://www.tokyuhotels.co.jp/sapporo-e/",
      URL_googlemap: "https://maps.google.com/?q=Sapporo+Excel+Hotel+Tokyu",
      previous_place_id: 6,
      arrive_time: "2026-08-11 17:30:00",
      departure_time: "2026-08-12 10:00:00",
      related_project_id: 1,
    },

    {
      id: 8,
      place_name: "京都駅 烏丸口地下ポルタ",
      type: "食事",
      detail:
        "京都に到着後、まずは腹ごしらえ。京うどんの「萬重」にて季節の天ぷらうどんを食べる。",
      item: "特になし",
      URL_photo: "https://images.example.com/kyoto-porta.jpg",
      URL_home: "https://www.porta.co.jp",
      URL_googlemap: "https://maps.google.com/?q=Kyoto+Station+Porta",
      previous_place_id: null,
      arrive_time: "2026-11-20 12:00:00",
      departure_time: "2026-11-20 13:00:00",
      related_project_id: 2,
    },
    {
      id: 9,
      place_name: "清水寺",
      type: "観光",
      detail:
        "清水の舞台からの紅葉を一望。清水坂で八つ橋の試食とお土産選び。階段が多いため両親のペースに合わせる。",
      item: "御朱印帳, 拝観料（現金のみ）",
      URL_photo: "https://images.example.com/kiyomizudera.jpg",
      URL_home: "https://www.kiyomizudera.or.jp",
      URL_googlemap: "https://maps.google.com/?q=Kiyomizu-dera",
      previous_place_id: 8,
      arrive_time: "2026-11-20 13:45:00",
      departure_time: "2026-11-20 16:00:00",
      related_project_id: 2,
    },
    {
      id: 10,
      place_name: "高台寺",
      type: "観光",
      detail:
        "秋の夜間特別拝観。臥龍池に映し出される逆さ紅葉のライトアップは必見。防寒対策をしっかりと。",
      item: "防寒着, カイロ",
      URL_photo: "https://images.example.com/kodaiji-lightup.jpg",
      URL_home: "https://www.kodaiji.com",
      URL_googlemap: "https://maps.google.com/?q=Kodaiji+Temple",
      previous_place_id: 9,
      arrive_time: "2026-11-20 17:30:00",
      departure_time: "2026-11-20 19:00:00",
      related_project_id: 2,
    },
    {
      id: 11,
      place_name: "京都嵐山温泉 花伝抄",
      type: "宿泊",
      detail:
        "貸切風呂が無料の宿。夕食はハーフバイキングと飲み放題付き。宿への到着が遅れる場合は連絡。",
      item: "着替え",
      URL_photo: "https://images.example.com/kadensho.jpg",
      URL_home: "https://www.hotespa.net/hotels/kadensho/",
      URL_googlemap:
        "https://maps.google.com/?q=Kyoto+Arashiyama+Onsen+Kadensho",
      previous_place_id: 10,
      arrive_time: "2026-11-20 20:00:00",
      departure_time: "2026-11-21 08:30:00",
      related_project_id: 2,
    },
    {
      id: 12,
      place_name: "嵯峨野トロッコ列車（トロッコ嵯峨駅）",
      type: "移動",
      detail:
        "保津川渓谷の紅葉を眺める観光列車。1ヶ月前に事前手配したリッチ号（5号車）の乗車券を持参。",
      item: "トロッコ乗車券（QRコード）",
      URL_photo: "https://images.example.com/torokko.jpg",
      URL_home: "https://www.sagano-kanko.co.jp",
      URL_googlemap: "https://maps.google.com/?q=Torokko+Saga+Station",
      previous_place_id: 11,
      arrive_time: "2026-11-21 08:50:00",
      departure_time: "2026-11-21 09:30:00",
      related_project_id: 2,
    },
    {
      id: 13,
      place_name: "渡月橋",
      type: "観光",
      detail:
        "嵐山のシンボル。桂川に架かる橋を背景に記念撮影。周辺の湯豆腐店で昼食の混雑具合を確認。",
      item: "自撮り棒",
      URL_photo: "https://images.example.com/togetsukyo.jpg",
      URL_home: "https://www.kyoto.travel",
      URL_googlemap: "https://maps.google.com/?q=Togetsukyo+Bridge",
      previous_place_id: 12,
      arrive_time: "2026-11-21 11:00:00",
      departure_time: "2026-11-21 12:30:00",
      related_project_id: 2,
    },
    {
      id: 14,
      place_name: "嵐山よしむら",
      type: "食事",
      detail:
        "渡月橋を眺めながら手打ち蕎麦を楽しめる人気店。窓側の席が取れるとベスト。",
      item: "特になし",
      URL_photo: "https://images.example.com/yoshimura-soba.jpg",
      URL_home: "http://www.arashiyama-yoshimura.com",
      URL_googlemap: "https://maps.google.com/?q=Arashiyama+Yoshimura",
      previous_place_id: 13,
      arrive_time: "2026-11-21 12:45:00",
      departure_time: "2026-11-21 14:00:00",
      related_project_id: 2,
    },

    {
      id: 15,
      place_name: "築地場外市場",
      type: "食事",
      detail:
        "朝食としてホルモン煮込みの「きつねや」か、海鮮丼の「まるきた」へ。食べ歩きのマナーに注意。",
      item: "ウェットティッシュ, 現金（1000円札多め）",
      URL_photo: "https://images.example.com/tsukiji.jpg",
      URL_home: "https://www.tsukiji.or.jp",
      URL_googlemap: "https://maps.google.com/?q=Tsukiji+Outer+Market",
      previous_place_id: null,
      arrive_time: "2026-05-30 08:00:00",
      departure_time: "2026-05-30 10:30:00",
      related_project_id: 3,
    },
    {
      id: 16,
      place_name: "浅草寺",
      type: "観光",
      detail:
        "雷門で記念撮影後、仲見世通りを散策。人形焼きをお土産に購入する。常香炉の煙を浴びる。",
      item: "小銭（お賽銭用）",
      URL_photo: "https://images.example.com/sensoji.jpg",
      URL_home: "https://www.senso-ji.jp",
      URL_googlemap: "https://maps.google.com/?q=Senso-ji+Temple",
      previous_place_id: 15,
      arrive_time: "2026-05-30 11:15:00",
      departure_time: "2026-05-30 13:00:00",
      related_project_id: 3,
    },
    {
      id: 17,
      place_name: "浅草 今半 国際通り本店",
      type: "食事",
      detail:
        "贅沢ランチとして明治創業の老舗で「すき焼き御膳」を堪能する。事前のWeb予約を要確認。",
      item: "予約確認メール",
      URL_photo: "https://images.example.com/imahan.jpg",
      URL_home: "https://www.asakusaimahan.co.jp",
      URL_googlemap: "https://maps.google.com/?q=Asakusa+Imahan",
      previous_place_id: 16,
      arrive_time: "2026-05-30 13:15:00",
      departure_time: "2026-05-30 15:00:00",
      related_project_id: 3,
    },
    {
      id: 18,
      place_name: "東京スカイツリー",
      type: "観光",
      detail:
        "天望デッキ（地上350m）からの展望を楽しむ。夕方から夜にかけての景色を狙うため、この時間帯に設定。",
      item: "展望台eチケット（15:45入場回）",
      URL_photo: "https://images.example.com/skytree.jpg",
      URL_home: "https://www.tokyo-skytree.jp",
      URL_googlemap: "https://maps.google.com/?q=Tokyo+Skytree",
      previous_place_id: 17,
      arrive_time: "2026-05-30 15:45:00",
      departure_time: "2026-05-30 18:30:00",
      related_project_id: 3,
    },
    {
      id: 19,
      place_name: "月島もんじゃ ストリート",
      type: "食事",
      detail:
        "夕食。「もんじゃ 蔵」か「もへじ」を訪問。人気店のため並ぶ可能性あり。衣服への匂い移りに注意。",
      item: "消臭スプレー（ホテル常備品）",
      URL_photo: "https://images.example.com/monja-street.jpg",
      URL_home: "https://monja.gr.jp",
      URL_googlemap: "https://maps.google.com/?q=Tsukishima+Monja+Street",
      previous_place_id: 18,
      arrive_time: "2026-05-30 19:15:00",
      departure_time: "2026-05-30 21:00:00",
      related_project_id: 3,
    },
    {
      id: 20,
      place_name: "三井ガーデンホテル銀座プレミア",
      type: "宿泊",
      detail:
        "高層階からの東京の夜景が見えるホテル。チェックイン後、部屋からの夜景を楽しみつつ明日のプランを練る。",
      item: "身分証明書",
      URL_photo: "https://images.example.com/mitsui-garden-ginza.jpg",
      URL_home: "https://www.gardenhotels.co.jp/ginza-premier/",
      URL_googlemap:
        "https://maps.google.com/?q=Mitsui+Garden+Hotel+Ginza+Premier",
      previous_place_id: 19,
      arrive_time: "2026-05-30 21:30:00",
      departure_time: "2026-05-31 11:00:00",
      related_project_id: 3,
    },
  ]);
};
