/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("task").del();
  await knex("task").insert([
    {
      id: 1,
      IsMovement: false,
      sequence: 1,
      type: "Hotel",
      name: "ホテルチェックアウト",
      detail: "出発の準備を整えてロビーでチェックアウト手続き。",
      URL_photo: null,
      URL_home: "https://example-hotel.com",
      URL_googlemap: "https://goo.gl/maps/hotel",
      arrive_time: "2026-06-01T08:00:00Z",
      departure_time: "2026-06-01T08:15:00Z",
      related_project_id: 1,
    },
    {
      id: 2,
      IsMovement: true,
      sequence: 2,
      type: "walk",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T08:15:00Z",
      departure_time: "2026-06-01T08:30:00Z",
      related_project_id: 1,
    },
    {
      id: 3,
      IsMovement: true,
      sequence: 3,
      type: "train",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T08:30:00Z",
      departure_time: "2026-06-01T09:30:00Z",
      related_project_id: 1,
    },
    {
      id: 4,
      IsMovement: true,
      sequence: 4,
      type: "flight",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T09:30:00Z",
      departure_time: "2026-06-01T11:00:00Z",
      related_project_id: 1,
    },
    {
      id: 5,
      IsMovement: false,
      sequence: 5,
      type: "Meal",
      name: "空港到着・早めのランチ",
      detail: "到着ロビー近くのレストランで食事。",
      URL_photo: "https://example.com/photo/lunch.jpg",
      URL_home: null,
      URL_googlemap: "https://goo.gl/maps/airport-restaurant",
      arrive_time: "2026-06-01T11:00:00Z",
      departure_time: "2026-06-01T12:00:00Z",
      related_project_id: 1,
    },
    {
      id: 6,
      IsMovement: true,
      sequence: 6,
      type: "car",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T12:00:00Z",
      departure_time: "2026-06-01T12:30:00Z",
      related_project_id: 1,
    },
    {
      id: 7,
      IsMovement: false,
      sequence: 7,
      type: "Sightseeing",
      name: "市立美術館の特別展",
      detail: "事前予約したチケットで入場し、展示を回る。",
      URL_photo: "https://example.com/photo/museum.jpg",
      URL_home: "https://example-museum.com",
      URL_googlemap: "https://goo.gl/maps/museum",
      arrive_time: "2026-06-01T12:30:00Z",
      departure_time: "2026-06-01T14:30:00Z",
      related_project_id: 1,
    },
    {
      id: 8,
      IsMovement: true,
      sequence: 8,
      type: "walk",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T14:30:00Z",
      departure_time: "2026-06-01T14:45:00Z",
      related_project_id: 1,
    },
    {
      id: 9,
      IsMovement: false,
      sequence: 9,
      type: "Cafe",
      name: "駅前のカフェで休憩",
      detail: "コーヒーを飲みながら次の予定を確認する。",
      URL_photo: null,
      URL_home: null,
      URL_googlemap: "https://goo.gl/maps/cafe",
      arrive_time: "2026-06-01T14:45:00Z",
      departure_time: "2026-06-01T15:30:00Z",
      related_project_id: 1,
    },
    {
      id: 10,
      IsMovement: true,
      sequence: 10,
      type: "train",
      name: null,
      detail: null,
      URL_photo: null,
      URL_home: null,
      URL_googlemap: null,
      arrive_time: "2026-06-01T15:30:00Z",
      departure_time: "2026-06-01T16:00:00Z",
      related_project_id: 1,
    },
  ]);
};
