/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  const now = new Date().toISOString();
  // Deletes ALL existing entries
  await knex("cost").del();
  await knex("cost").insert([
    {
      id: 1,
      type: "交通費",
      related_project_id: 1,
      related_task_id: null,
      cost: 45000.0,
      currency: "JPY",
      date_of_used: "2026-06-01 09:30:00",
      date_of_add: now,
    },
    {
      id: 2,
      type: "宿泊費",
      related_project_id: 1,
      related_task_id: 1,
      cost: 12000.0,
      currency: "JPY",
      date_of_used: "2026-06-01 08:00:00",
      date_of_add: now,
    },
    {
      id: 3,
      type: "交通費",
      related_project_id: 1,
      related_task_id: 3,
      cost: 650.0,
      currency: "JPY",
      date_of_used: "2026-06-01 08:30:00",
      date_of_add: now,
    },
    {
      id: 4,
      type: "食費",
      related_project_id: 1,
      related_task_id: 5,
      cost: 2500.0,
      currency: "JPY",
      date_of_used: "2026-06-01 11:15:00",
      date_of_add: now,
    },
    {
      id: 5,
      type: "交通費",
      related_project_id: 1,
      related_task_id: 6,
      cost: 3800.0,
      currency: "JPY",
      date_of_used: "2026-06-01 12:00:00",
      date_of_add: now,
    },
    {
      id: 6,
      type: "交際費",
      related_project_id: 1,
      related_task_id: 7,
      cost: 1800.0,
      currency: "JPY",
      date_of_used: "2026-06-01 12:30:00",
      date_of_add: now,
    },
    {
      id: 7,
      type: "食費",
      related_project_id: 1,
      related_task_id: 9,
      cost: 850.0,
      currency: "JPY",
      date_of_used: "2026-06-01 15:00:00",
      date_of_add: now,
    },
    {
      id: 8,
      type: "交通費",
      related_project_id: 1,
      related_task_id: 10,
      cost: 420.0,
      currency: "JPY",
      date_of_used: "2026-06-01 15:40:00",
      date_of_add: now,
    },
    {
      id: 9,
      type: "雑費",
      related_project_id: 1,
      related_task_id: null,
      cost: 500.0,
      currency: "JPY",
      date_of_used: "2026-06-01 10:00:00",
      date_of_add: now,
    },
    {
      id: 10,
      type: "お土産代",
      related_project_id: 1,
      related_task_id: null,
      cost: 5500.0,
      currency: "JPY",
      date_of_used: "2026-06-01 16:30:00",
      date_of_add: now,
    },
  ]);
};
